[project]
name = "cloud-info-sys"
version = "0.1.0"
description = "A cloud info API implementation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
]
