#cloud-config
---
# avoid auto-upgrade kicking off in the first boot
bootcmd:
  - [cloud-init-per, once, touch, /var/lib/apt/periodic/update-success-stamp]

users:
  - name: egi
    gecos: EGI
    primary_group: egi
    groups: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:enolfc
      - gh:gwarf
      - gh:CatalinCondurache
      - gh:sebastian-luna-valero
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEmO16+MOcZwomZUZ+68rcmXcCs95hVB6u1TD6y6bD7t cloud-info-api
